"""remover colunas confir_senha

Revision ID: 6770198ffd7d
Revises: ea6e6ecf7a64
Create Date: 2026-08-09 14:20:23.389773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6770198ffd7d'
down_revision: Union[str, Sequence[str], None] = 'ea6e6ecf7a64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usuario', 'confir_senha')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usuario', sa.Column('confir_senha', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
